services:
    postgres:
      image: postgres:bookworm
      container_name: postgres-db
      environment:
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=postgres
        - POSTGRES_DB=dual_sync_db
      networks:
        - dbSync_network
      volumes:
        - postgres-data:/var/lib/postgresql/data
      ports:
        - "5433:5432"
    
    mongo:
      image: mongo:7.0
      container_name: mongo-db
      environment:
        - MONGODB_URI=${MONGODB_URI}
      networks:
        - dbSync_network
      volumes:
        - mongo-data:/data/db
      ports:
        - "27017:27017"
    
    backend:
      build: 
        context: .
        dockerfile: Dockerfile
      container_name: backend_app
      restart: unless-stopped
      ports:
        - "3000:5000"
      env_file:
        - .env
      networks:
        - dbSync_network
      depends_on:
      - postgres
      - mongo
volumes:
  postgres-data:
  mongo-data:
       
networks:
  dbSync_network:
    driver: bridge