version: '3.8'

services:
    postgres:
      image: postgres:latest
      container_name: postgres-db
      environment:
        - POSTGRES_URI=${POSTGRES_URI}
      networks:
        - dbSync_network
      ports:
        - "5432:5432"
      volumes:
        - postgres-data:/var/lib/postgresql/data
    
    mongo:
      image: mongo:latest
      container_name: mongo-db
      environment:
        - MONGODB_URI=${MONGODB_URI}
      networks:
        - dbSync_network
      ports:
        - "27017:27017"
      volumes:
        - mongo-data:/data/db
    
    backend:
      build: ./backend
      container_name: backend_app
      ports:
        - "3000:3000"
      env_file:
        - ./backend/.env
      networks:
        - dbSync_network
      depends_on:
      - postgres
      - mongo
volumes:
  postgres_data:
  mongo_data:
       
networks:
  dbSync_network:
    driver: bridge